apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync  
    argocd.argoproj.io/sync-wave: "1"
  namespace: production
  name: hns-argo-test-pg
