apiVersion: v1
kind: Service
metadata:
  annotations:    
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: HookFailed    
  name: my-service
  namespace: production
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
