apiVersion: v1
kind: Service
metadata:
  annotations:    
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
  name: my-service
  namespace: hns-argo-test-pg
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
